-- Crop calendar data
USE eco_farm_manager;

INSERT INTO crop_calendar (crop_name, scientific_name, planting_season, harvesting_season, duration_days, soil_type, temperature_range, rainfall_requirement, key_activities, optimal_conditions, region) VALUES
('Rice', 'Oryza sativa', 'June-July (Kharif), December-January (Rabi)', 'October-November (Kharif), April-May (Rabi)', 120, 'Clay/Loamy', '20-35°C', '1200-1500mm', 'Land preparation, nursery raising, transplanting, weeding, fertilization, pest control, harvesting', 'Flooded fields, warm and humid climate, pH 5.5-6.5', 'India, Southeast Asia'),
('Wheat', 'Triticum aestivum', 'October-November (Rabi), March-April (Summer)', 'March-April (Rabi), June-July (Summer)', 120, 'Loamy', '15-20°C', '450-650mm', 'Seed bed preparation, sowing, irrigation, fertilization, pest control, harvesting', 'Well-drained soil, cool climate during growth, warm during grain filling', 'North India, Temperate regions'),
('Maize', 'Zea mays', 'June-July (Kharif), February-March (Rabi)', 'September-October (Kharif), May-June (Rabi)', 90, 'Well-drained Loamy', '20-30°C', '500-800mm', 'Land preparation, sowing, thinning, fertilization, irrigation, pest control, harvesting', 'Sunny weather, adequate moisture, pH 6.0-7.0', 'All India, Tropical/Subtropical'),
('Cotton', 'Gossypium spp.', 'April-May (Kharif), August-September (Summer)', 'November-December (Kharif), January-February (Summer)', 150, 'Black/Red soil', '25-35°C', '600-1000mm', 'Seed treatment, sowing, thinning, fertilization, pest management, defoliation, harvesting', 'Warm climate, well-drained soil, adequate sunlight', 'Maharashtra, Gujarat, Andhra Pradesh'),
('Sugarcane', 'Saccharum officinarum', 'February-March (Spring), September-October (Autumn)', 'December-March (Spring), July-November (Autumn)', 300, 'Deep fertile soil', '20-35°C', '1500-2500mm', 'Land preparation, sett treatment, planting, earthing up, fertilization, irrigation, harvesting', 'Fertile soil, adequate water, tropical climate', 'Uttar Pradesh, Maharashtra, Karnataka'),
('Potatoes', 'Solanum tuberosum', 'September-October (Autumn), January-February (Spring)', 'January-February (Autumn), April-May (Spring)', 90, 'Sandy Loam', '15-20°C', '500-700mm', 'Seed treatment, ridge making, planting, earthing up, fertilization, irrigation, harvesting', 'Cool climate, loose soil, adequate moisture', 'Hills of North India, West Bengal'),
('Tomatoes', 'Solanum lycopersicum', 'June-July (Kharif), December-January (Rabi)', 'October-November (Kharif), March-April (Rabi)', 120, 'Well-drained Loamy', '20-25°C', '600-800mm', 'Nursery raising, transplanting, staking, fertilization, pest control, harvesting', 'Warm climate, well-drained soil, full sunlight', 'All India, Protected cultivation'),
('Onions', 'Allium cepa', 'September-October (Kharif), January-February (Rabi)', 'January-February (Kharif), April-May (Rabi)', 120, 'Fertile Loamy', '15-25°C', '400-600mm', 'Seed treatment, sowing/transplanting, thinning, fertilization, irrigation, harvesting', 'Mild climate, fertile soil, good drainage', 'Maharashtra, Karnataka, Tamil Nadu'),
('Chillies', 'Capsicum annuum', 'January-February (Rabi), June-July (Kharif)', 'April-May (Rabi), September-October (Kharif)', 150, 'Well-drained Loamy', '20-30°C', '600-800mm', 'Nursery raising, transplanting, fertilization, pest control, harvesting', 'Warm climate, adequate moisture, full sunlight', 'Andhra Pradesh, Karnataka, West Bengal'),
('Groundnut', 'Arachis hypogaea', 'June-July (Kharif), January-February (Rabi)', 'September-October (Kharif), April-May (Rabi)', 120, 'Sandy Loam', '25-30°C', '500-700mm', 'Seed treatment, sowing, fertilization, weed control, pest management, harvesting', 'Warm climate, well-drained sandy soil', 'Gujarat, Andhra Pradesh, Tamil Nadu'),
('Soybean', 'Glycine max', 'June-July (Kharif), February-March (Spring)', 'October-November (Kharif), May-June (Spring)', 100, 'Well-drained Loamy', '20-30°C', '600-800mm', 'Seed treatment, sowing, fertilization, irrigation, pest control, harvesting', 'Warm humid climate, well-drained soil', 'Madhya Pradesh, Maharashtra, Rajasthan'),
('Turmeric', 'Curcuma longa', 'April-May (Summer), August-September (Kharif)', 'January-March (Summer), January-March (Kharif)', 240, 'Rich Loamy', '20-30°C', '1500-2000mm', 'Rhizome treatment, planting, mulching, fertilization, irrigation, harvesting', 'Humid climate, partial shade, rich organic soil', 'Andhra Pradesh, Odisha, West Bengal'),
('Ginger', 'Zingiber officinale', 'March-April (Summer), August-September (Kharif)', 'December-February (Summer), December-February (Kharif)', 240, 'Rich Loamy', '20-30°C', '1500-2000mm', 'Rhizome treatment, planting, mulching, fertilization, irrigation, harvesting', 'Humid climate, partial shade, rich organic soil', 'Kerala, Karnataka, West Bengal');